### ISSUE TITLE
Content type definition incorrectly prefers depth over priorty

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform#351] opened 2023-03-08 19:32 UTC
If you open a .hpp file in Eclipse with both CDT and TM4E installed it opens in the generic editor instead of the CEditor.

My reading of the TM4E code is that the intention was that the language_pack definitions were supposed to be lower [priority](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_core_contenttype_contentTypes.html) that things the user already had installed.

However, it turns out that the way Eclipse chooses a content type depends on the ["depth"](https://github.com/eclipse-platform/eclipse.platform/blob/9839c18f52687db6f949bdb56a59a5d20cd7c938/runtime/bundles/org.eclipse.core.contenttype/src/org/eclipse/core/internal/content/ContentTypeCatalog.java#L43-L60) of the content type by considering how many base types it has. And CDT's content type for .hpp files is deeper than TM4E's one.

As far as I can tell, depth is not documented as an important factor even though it is implemented that way. priority is documented as such:

> priority - the priority for this content type. Priorities are used to solve conflicts (when two content types are associated to the same file name/extension)

**Comment by mickaelistria** [comment] 2023-03-09 09:10
> As far as I can tell, depth is not documented as an important factor

Indeed depth is not an important factor per se, the important factor is to return "most specialized" content-type in a lineage, ie basicContentType(priority=high) being a parent of specializedContentType(priority=low), then querying a file which has both content-type should return specializedContentType independently of the priority. That is what enables the most value.
Depth was an implementation choice to achieve that, but it doesn't make sense to use it when the content-types we compare are not of the same lineage: basicContentType has 2 independent children specializedContentType1(priority=high) and specializedContentType2(priority=normal) and that one has a child surSpecializedContentType2(priority=normal), then the expectation is that specializedContentType1 is returned first because depth isn't an interesting criterion to compare specializedContentType1 and surSpecializedContentType2.

An implication of both is this trickier case:
basicContentType
  * specializedContentType1(priority=high)
    * surSpecializedContentType1(priority=low)
  * specializedContentType2(priority=normal)
    * surSpecializedContentType2(priority=normal)
 
Then we would expect that the best content-type here is surSpecializedContentType1. Basically, to fulfill both requirements the priority of a content-type is the max of its lineage.

**Comment by mickaelistria** [comment] 2023-03-14 22:48
I'm closing it as a duplicate of #151 , most of the interesting bits discussed here are also copied in #350 so I don't think we lose anything by closing it. If you disagree, feel free to reopen.

**Closed by mickaelistria** 2023-03-14 22:48 UTC
