### ISSUE TITLE
Random failing IJobManagerTest.testOrder

### ISSUE THREAD

**Issue by Michael5601** [eclipse-platform/eclipse.platform#628] opened 2023-08-08 08:59 UTC
The test case `org.eclipse.core.tests.runtime.jobs.IJobManagerTest.testOrder` randomly fails:
https://github.com/eclipse-platform/eclipse.platform/pull/625/checks?check_run_id=15677878481
```java
1.1.0 expected:<testOrder(0)(418)> but was:<testOrder(1)(419)>
junit.framework.AssertionFailedError: 1.1.0 expected:<testOrder(0)(418)> but was:<testOrder(1)(419)>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.TestCase.assertEquals(TestCase.java:238)
	at org.eclipse.core.tests.runtime.jobs.IJobManagerTest.testOrder(IJobManagerTest.java:1772)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
```
Locally this test does not fail with my setup. But in PR #625 it failed.

**Comment by fedejeanne** [comment] 2023-08-08 12:31
This looks a lot like the race condition that `testReverseOrder` suffered from (which was fixed in https://github.com/eclipse-platform/eclipse.platform/commit/060e9361f8f62c0cb1d15f079cfe576e7b0af6a8)

**Comment by HeikoKlare** [comment] 2023-09-04 07:26
The issue is different from `testReverseOrder`. The reverse order test checks that scheduling jobs with delays lower than the remaining delays of already scheduled tests will result in executing the later scheduled jobs first (i.e. that the delay is considered properly). The issue with that test was that it had no guarantee that later scheuled jobs have a delay lower than the already scheduled ones (because the `main` thread is "too slow). The ordinary `testOrder` case validates that jobs scheduled with increasing delays are executed in the order in which they are scheduled, i.e., that no "time travels" occur. Thus it cannot suffer from the `main` thread being "too slow".

I expect the reason for the failing test to be its faulty test condition: the test does _not_ validate whether the jobs are scheduled in the expected order, but that their first statement is executed in the expected order. This is not guaranteed (and should not be as well), so the test suffers from a race condition.
I propose to use an `IJobChangeListener` to get notified about Job state changes, which is what is supposed to validated in the test case.

I will provide a PR to fix.

**Comment by HeikoKlare** [comment] 2023-09-04 10:53
Unfortunately the `IJobChangeListener` cannot be used, as it is (correctly) notified in an unsynchronized environment, i.e., there is no guarantee that events are propagated to the listener in the "correct" order.

Only the actual state changes of the jobs are performed in a synchronized environment and can thus be used for validating orders. I propose to change the test such that it validates that once a job runs it predecessors (i.e. earlier scheduled jobs) have also started running in any way, which means that their state changed from SLEEPING to either RUNNING (including ABOUT_TO_RUN) or NONE. See #655.

**Closed** 2023-09-11 13:49 UTC
