### ISSUE TITLE
Make Text Compare more smart

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#66] opened 2022-06-21 06:30 UTC
I recently noticed that text-compare seems to present a undesirable changeset if the following happen:

1. You have some repeated code block  with common start (e.g. `<dependency>` in a pom.xml or `@Test` in a Unit test) and ending (e.g. `</dependency>` in a pom.xml or `}` in a Unit test
2. You insert a new block in between
3. Now the change set spans into the next block

![grafik](https://user-images.githubusercontent.com/1331477/174729794-fad66f74-3d98-4e3e-aa90-05db79fd2e1e.png)

**What would be expected is that the whole block is marked as an insertion (here line 74 - 78)**

Github for example displays this more nice

![grafik](https://user-images.githubusercontent.com/1331477/174731417-3eaa11a0-aa9c-4e00-bb5b-e9f5ed582191.png)

**Comment by jukzi** [comment] 2023-01-25 14:12
@laeubi would you please test the proposed fix if it fits your request?

**Comment by jukzi** [comment] 2023-01-27 15:16
won't fix

**Comment by laeubi** [comment] 2023-01-27 15:24
@jukzi why won't fix?

**Comment by jukzi** [comment] 2023-01-27 15:50
well, no one seems to take the time to implement or even test.

**Comment by laeubi** [comment] 2023-01-27 15:54
I'm a bit short of time atm, but even if not two days are really not an indication of no interest, I think its still worth and your code should not be lost ...

**Comment by Bananeweizen** [comment] 2023-01-29 14:03
The diff algorithm is based on finding longest common subsequences (LCS) between both files. By design, that will always make the common (unchanged) parts as _large_ as possible. To make the result more human readable, the changes created by the LCS would have to be post-processed to create more _balanced_ (instead of longest) common subsequences between the changes. A simple heuristic would be to modify all changes where there are identical _lines_ at the end of the change and immediately before the change, and where the first line of a change has different indentation than the last line, and where that does not overlap with another change.
I'll check if I can get that working...

**Closed** 2023-04-17 11:08 UTC

**Comment by jukzi** [comment] 2024-09-06 08:53
Seems like line based diff like LCS is unsuitable for tree structure documents. There are more advanced algorithms for xml. See for example: [X-Diff: An Effective Change Detection Algorithm for XML](https://resources.mpi-inf.mpg.de/d5/teaching/ss03/xml-seminar/Material/wang_icde2003.pdf)
