### ISSUE TITLE
Failure of LinkTest.testAllLinks()

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#561] opened 2023-07-04 09:10 UTC
The test failed in [this run](https://github.com/eclipse-platform/eclipse.platform/actions/runs/5452492617/jobs/9920076530?pr=560) of the PR #560 

```
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: %20http://wiki.eclipse.org/Execution_Environment_Descriptions
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: %20http://wiki.eclipse.org/Execution_Environment_Descriptions
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.testAllLinks(LinkTest.java:82)
...
```

**Comment by fedejeanne** [comment] 2023-07-05 13:30
Failed again in #563

**Comment by fedejeanne** [comment] 2023-07-06 12:33
Does anyone know how to test this locally?

I tried following this guide but it's outdated/unclear: https://github.com/eclipse-platform/eclipse.platform/tree/master/ua/infocenter-web

**Comment by merks** [comment] 2023-07-06 12:45
I can run this test locally, but it doesn't run well at all:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/19f9bf76-b95d-402a-b0e6-9a8105661806)

I think very likely the two highlighted space characters in these two files are the cause of problem:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/886e5c30-91a6-43ff-8ec9-cd15df8d6dd8)

**Comment by fedejeanne** [comment] 2023-07-06 13:31
Thanks for the tip!
I also run into the same exception when running the tests (`FileNotFoundException`) and I think it's because there is no WebServer running so there is no _online help_ at all.

I removed the whitespaces in #271 .

**Comment by jukzi** [comment] 2023-07-08 18:59
> I removed the whitespaces in #271 .

277 ?

**Comment by Bananeweizen** [comment] 2023-07-09 08:13
A fix is ready to be merged in https://github.com/eclipse-platform/eclipse.platform/pull/566. I'd just like to get a second opinion on my claim that the test code is actually wrong, because blanks _are_ allowed around URIs in HTML.

**Comment by jukzi** [comment] 2023-07-09 11:08
For (x)html5 a whitspace is explicitly allowed "A string is a valid URL potentially surrounded by spaces if, after stripping leading and trailing whitespace (https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#strip-leading-and-trailing-whitespace) from it, it is a valid URL."
For html4 it was not: "href = [uri](https://www.w3.org/TR/html401/types.html#type-uri) [[CT]](https://www.w3.org/TR/html401/types.html#see-type-for-case)"

**Comment by HannesWell** [comment] 2023-07-09 11:15
> For (x)html5 a whitspace is explicitly allowed "A string is a valid URL potentially surrounded by spaces if, after stripping leading and trailing whitespace (https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#strip-leading-and-trailing-whitespace) from it, it is a valid URL." For html4 it was not: "href = [uri](https://www.w3.org/TR/html401/types.html#type-uri) [[CT]](https://www.w3.org/TR/html401/types.html#see-type-for-case)"

If all documents use HTML-5, then I think it would be OK to ignore leading/failing white-space in the test.

**Comment by HannesWell** [comment] 2023-07-09 13:01
> But the question is of course, do they all use HTML-5?

The doc-type of the help-page is `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">`, so it looks like this is html 4. What a bummer.

However I wonder why the updates in the extension-point schema definitions are not incorporated immediately into the help?
Even in my Eclipse SDK with Build id: I20230708-1800 (which is the latest build, the leading space is still present).

**Comment by laeubi** [comment] 2023-07-09 13:39
> The doc-type of the help-page is <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">, so it looks like this is html 4. What a bummer.

https://github.com/eclipse-platform/www.eclipse.org-eclipse/issues/43

> However I wonder why the updates in the extension-point schema definitions are not incorporated immediately into the help?

Have you bumped the doc bundles?

**Comment by HannesWell** [comment] 2023-07-09 15:04
> > The doc-type of the help-page is , so it looks like this is html 4. What a bummer.
> 
> [eclipse-platform/www.eclipse.org-eclipse#43](https://github.com/eclipse-platform/www.eclipse.org-eclipse/issues/43)

That would be nice.

> 
> > However I wonder why the updates in the extension-point schema definitions are not incorporated immediately into the help?
> 
> Have you bumped the doc bundles?

Yes, that was (very like) the problem. Thanks for the hint!
 Just merged https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1209 and the result looks promosing. After tonight's I-build this issue should be gone.

Keep this issue open until then.

**Closed** 2023-07-10 06:16 UTC

**Comment by HannesWell** [comment] 2023-07-10 06:28
Build is green now.
Thanks to everyone who participated!
