### ISSUE TITLE
org.osgi.service.http: Unable to satisfy dependency 

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#969] opened 2023-12-08 20:24 UTC
The jenkins console log contains 525 times the same warning https://ci.eclipse.org/platform/job/eclipse.platform/job/master/lastBuild/console

    [WARNING] Problems resolving provisioning plan.: [Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).]
 

```
Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).;
Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).;
Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).
``` 

Can someone solve that? I also get a similar warning when i start workspace locally
minor: why is it printed so many times?

**Comment by merks** [comment] 2023-12-08 20:58
It would be so nice to have warning free builds. After all, a warning is a cry to be fixed.

**Comment by laeubi** [comment] 2023-12-09 05:37
> Can someone solve that?

Se the current ongoing work here
- https://github.com/eclipse-equinox/equinox/pull/403

> why is it printed so many times?

Because it happens on each project when it gets resolved and for each platform and then maybe when tests are resolved as well, this is similar to another warning you you repeatedly in the logs

```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:/home/jenkins/agent/workspace/eclipse.platform_master/ant/org.eclipse.ant.tests.ui/target/work/configuration/org.eclipse.osgi/59/0/.cp/lib/antsupportlib.jar)
WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
WARNING: System::setSecurityManager will be removed in a future release
```

**Comment by iloveeclipse** [comment] 2023-12-12 15:30
Can we please either fix these maven warnings or to disable the "quality" gate?
It makes no sense to keep reporting errors that are not caused by PR's on every PR.

**Comment by laeubi** [comment] 2023-12-12 15:53
Feel free to contribute if you want to fix the issue reported **here**:
- https://github.com/eclipse-equinox/equinox/pull/403

Anyways these reported **here** are not "maven" warnings but warnings reported by P2 because the resolution might be incomplete, Tycho just forwards these warnings to the user so they got not lost unnoticed.

Beside that the ones that are reported at the build [you recently referenced](https://github.com/eclipse-platform/eclipse.platform/pull/1002) are cause because platform+platform.ui has heavy cyclic dependencies and test *might* give different results as they do not specify the reactor dependencies directly but only indirect, what might be an issue that one could/should fix, se the message for details about the offending plugins.

**Comment by jukzi** [comment] 2023-12-12 16:02
I vote disable quality gate for maven until issue is fixed if ETA not soon 

Jörg Kubitz

**Comment by iloveeclipse** [comment] 2023-12-12 16:12
> Feel free to contribute if you want to fix the issue reported **here**

I've checked this code and I'm not qualified to work on that.

> I vote disable quality gate for maven until issue is fixed if ETA not soon

I second that. I can't see these errors anymore (for no **obvious** reason).

**Comment by laeubi** [comment] 2023-12-13 05:44
> I second that. I can't see these errors anymore (for no obvious reason).

If something is unclear please ask, these warnings won't go away by just ignoring them. _This_ issue and the linked one are about _multiple_ warnings about "Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to", this is already fixed here:

- https://github.com/eclipse-tycho/tycho/pull/3228

so one should only ever see this warning once per project and as such it should never be any "new" (in comparison to the reference build).

**Comment by HannesWell** [comment] 2023-12-18 22:34
This is now fixed temporarily with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1672 and permanently with https://github.com/eclipse-equinox/equinox/pull/403 so https://github.com/eclipse-platform/eclipse.platform/pull/1007 can be reverted.

**Closed by HannesWell** 2023-12-18 22:34 UTC
Labels: bug, dependencies
