### ISSUE TITLE
LaunchTests.testProcessLaunchWithLongWorkingDirectory() fails in I-Builds on linux

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1505] opened 2024-08-14 07:45 UTC
for example https://download.eclipse.org/eclipse/downloads/drops4/I20240805-1800/testresults/html/org.eclipse.debug.tests_ep433I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html
```
org.eclipse.core.runtime.CoreException: Exception occurred executing command line.
at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:1015)
at org.eclipse.debug.tests.launching.LaunchTests.startProcessAndAssertOutputContains(LaunchTests.java:155)
at org.eclipse.debug.tests.launching.LaunchTests.testProcessLaunchWithLongWorkingDirectory(LaunchTests.java:150)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: java.io.IOException: Cannot run program "java" (in directory "/home/jenkins/agent/workspace/AutomatedTests/ep433I-unit-cen64-gtk3-java17/tmp/junit2686835052834504437/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name"): error=2, No such file or directory
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at java.base/java.lang.Runtime.exec(Runtime.java:594)
at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:1011)
... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
... 6 more
```

test was recently added by https://github.com/eclipse-platform/eclipse.platform/pull/1477 @HannesWell

**Comment by iloveeclipse** [comment] 2024-08-14 16:08
Duplicate of https://github.com/eclipse-platform/eclipse.platform/issues/1488

**Closed by iloveeclipse** 2024-08-14 16:08 UTC
Labels: bug, Linux, regression, test
