### ISSUE TITLE
Can't update anymore... 

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse-platform/eclipse.platform#44] opened 2022-07-12 08:34 UTC
Almost every current eclipse version (Java, J2EE, PDT/PHP) has that problem... 
![234234](https://user-images.githubusercontent.com/42765391/178447291-4529f7fb-b0be-4e8f-92da-a51853bb1833.jpg)
![343434](https://user-images.githubusercontent.com/42765391/178447298-28ea1abc-330e-4b62-8223-d881a04d85b2.jpg)
![1 jpg111](https://user-images.githubusercontent.com/42765391/178447301-7ccc42f5-53a6-4b22-a5da-102415ba17d5.jpg)

**Comment by mickaelistria** [comment] 2022-07-12 08:36
Can you provide steps to reproduce the issue?

**Comment by jayjupdhig** [comment] 2022-07-12 08:53
**_"Eclipse PDT was FRESHLY (!!) installed from eclipse.org in that version"_**

Today... ;-)

**Comment by mickaelistria** [comment] 2022-07-12 09:34
Is everything installed in a directory where you have write access?

**Comment by jayjupdhig** [comment] 2022-07-12 10:20
I think so... i don't used "Run as Administrator" - because i never needed that since i use Eclipse.

-> MAYBE the ultra-new Zulu Java 17 JDK / JRE is the problem...?

**Comment by jayjupdhig** [comment] 2022-07-12 10:21
Eclipse C/C++ is in the same directory but i does not have that package conflicts...?

Version:

Eclipse IDE for C/C++ Developers (includes Incubating components)

Version: 2022-06 (4.24.0)
Build id: 20220609-1112

**Comment by mickaelistria** [comment] 2022-07-12 10:27
I'm closing this here because the issue is not with Eclipse Platform or Eclipse SDK; but seems to originate from the packages. Here is the page that describes how to report issues for packages: https://projects.eclipse.org/projects/technology.packaging/developer

**Closed by mickaelistria** 2022-07-12 10:27 UTC

**Comment by jayjupdhig** [comment] 2022-07-12 10:34
OK thx, i've submitted it HERE:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=580364
