### ISSUE TITLE
NPE during "Refreshing Workspace" - IFileStore.getFileSystem()" is null - often when switching between git branches 

### ISSUE THREAD

**Issue by chrisrueger** [eclipse-platform/eclipse.platform#1114] opened 2024-01-22 11:29 UTC
This is a copy of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1886 because I opened it in the wrong repo (with my other account). 

There has already been a PR by @jukzi  related to this:  https://github.com/eclipse-platform/eclipse.platform/pull/1111 

Original issue description: 

I recently noticed the following exception quite often when switching between git branches (using external Github Desktop git client... not Eclipse itself)
Probably because the underlying filesystem content has changed. But maybe the NPE can be handled. 

I cannot remember seeing this exception much earlier.. so from a gut feeling I would say I noticed it in 2023-12. 

## Exception

An internal error occurred during: "Refreshing workspace".

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.filesystem.IFileSystem.getScheme()" because the return value of "org.eclipse.core.filesystem.IFileStore.getFileSystem()" is null
	at org.eclipse.core.internal.filesystem.FileStoreUtil.compareFileStore(FileStoreUtil.java:138)
	at org.eclipse.core.filesystem.IFileStore.compareTo(IFileStore.java:583)
	at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:344)
	at java.base/java.util.TreeMap.get(TreeMap.java:279)
	at org.eclipse.core.internal.resources.AliasManager$LocationMap.matchingResourcesDo(AliasManager.java:203)
	at org.eclipse.core.internal.resources.AliasManager.internalComputeAliases(AliasManager.java:545)
	at org.eclipse.core.internal.resources.AliasManager.computeAliases(AliasManager.java:430)
	at org.eclipse.core.internal.localstore.RefreshLocalAliasVisitor.deleteResource(RefreshLocalAliasVisitor.java:53)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.synchronizeExistence(RefreshLocalVisitor.java:195)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:302)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:119)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:1025)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:1008)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1610)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:228)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

## Environment 

```
eclipse.buildId=4.30.0.20231201-1200
java.version=17.0.9
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product -keyring .../.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.committers.product -keyring ....

This is a continuation of log file .../.metadata/.bak_5.log
Created Time: 2024-01-19 09:05:25.246

```

Let's make sure issue is not already fixed in latest builds first.

- [ ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* Switch the git branch outside of eclipse (e.g. with an external git client such as Github Desktop) so that Eclipse starts rebuilding because of the detected changes
* eclipse.buildId=4.30.0.20231201-1200
java.version=17.0.9
java.vendor=Eclipse Adoptium
* bndtools 7.0.0 Plugin 

I expected: no error

But got: 

`java.lang.NullPointerException: Cannot invoke "org.eclipse.core.filesystem.IFileSystem.getScheme()" because the return value of "org.eclipse.core.filesystem.IFileStore.getFileSystem()" is null`

![image](https://github.com/eclipse-platform/eclipse.platform/assets/188422/e94bad52-554e-44ba-8475-a7f747bc557d)

![image](https://github.com/eclipse-platform/eclipse.platform/assets/188422/991c328e-5cd4-4f2f-a17b-d11bd8c3cf39)

Before this stacktrace I see an output from bndtools builder (I am using bndtools).

The bndtools messages are from [here](https://github.com/bndtools/bnd/blob/master/bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java#L233) and [here](https://github.com/bndtools/bnd/blob/master/bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java#L271)

I don't know if they are the root cause. From the logs I can I only see that it does happen 2 seconds after the bndtools messages. I mentioned it to @pkriens of bndtools. He said he noticed this error too. 

```
!ENTRY bndtools.builder 1 0 2024-01-19 20:25:37.362
!MESSAGE BUILD AUTO my.project1 1 file was built in 0.153 sec
F/my.project1/src changed
project had changed files


!ENTRY bndtools.builder 1 0 2024-01-19 20:25:39.122
!MESSAGE BUILD AUTO my.project2 no build in 0.001 sec
F/my.project2/src changed
project had changed files
Blocking errors, leave old build files, quit


!ENTRY org.eclipse.core.jobs 4 2 2024-01-19 20:25:41.205
!MESSAGE An internal error occurred during: "Refreshing workspace".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.filesystem.IFileSystem.getScheme()" because the return value of "org.eclipse.core.filesystem.IFileStore.getFileSystem()" is null
	at org.eclipse.core.internal.filesystem.FileStoreUtil.compareFileStore(FileStoreUtil.java:138)
	at org.eclipse.core.filesystem.IFileStore.compareTo(IFileStore.java:583)
	at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:344)
	at java.base/java.util.TreeMap.get(TreeMap.java:279)
	at org.eclipse.core.internal.resources.AliasManager$LocationMap.matchingResourcesDo(AliasManager.java:203)
	at org.eclipse.core.internal.resources.AliasManager.internalComputeAliases(AliasManager.java:545)
	at org.eclipse.core.internal.resources.AliasManager.computeAliases(AliasManager.java:430)
	at org.eclipse.core.internal.localstore.RefreshLocalAliasVisitor.deleteResource(RefreshLocalAliasVisitor.java:53)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.synchronizeExistence(RefreshLocalVisitor.java:195)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:302)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:119)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:1025)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:1008)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1610)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:228)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY bndtools.builder 1 0 2024-01-19 20:25:42.211
!MESSAGE BUILD AUTO my.project3 no build in 0.002 sec
project has no or out-of-date target files
Blocking errors, leave old build files, quit


!ENTRY org.eclipse.core.jobs 4 2 2024-01-19 20:26:15.961
!MESSAGE An internal error occurred during: "Refreshing workspace".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.filesystem.IFileSystem.getScheme()" because the return value of "org.eclipse.core.filesystem.IFileStore.getFileSystem()" is null
	at org.eclipse.core.internal.filesystem.FileStoreUtil.compareFileStore(FileStoreUtil.java:138)
	at org.eclipse.core.filesystem.IFileStore.compareTo(IFileStore.java:583)
	at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:344)
	at java.base/java.util.TreeMap.get(TreeMap.java:279)
	at org.eclipse.core.internal.resources.AliasManager$LocationMap.matchingResourcesDo(AliasManager.java:203)
	at org.eclipse.core.internal.resources.AliasManager.internalComputeAliases(AliasManager.java:545)
	at org.eclipse.core.internal.resources.AliasManager.computeAliases(AliasManager.java:430)
	at org.eclipse.core.internal.localstore.RefreshLocalAliasVisitor.deleteResource(RefreshLocalAliasVisitor.java:53)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.synchronizeExistence(RefreshLocalVisitor.java:195)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:302)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:119)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:1025)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:1008)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1610)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:228)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY bndtools.builder 1 0 2024-01-19 20:26:16.630
!MESSAGE BUILD AUTO my.project4 1 file was built in 0.546 sec
F/my.project4/src changed
project had changed files
```

## Tested under this environment:
* OS & version: MacOS 14.2.1
* Eclipse IDE/Platform version (as shown in *Help > About*): 2023-12
* Bndtools 7.0

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by jukzi** [comment] 2024-01-22 11:34
tommorw you should be able to download a new I- version that gives more information

**Comment by pkriens** [comment] 2024-01-23 17:06
I ran into this in the Debugger. The Culprit is a NullFileStore. This calls:
```
	@Override
	public IFileSystem getFileSystem() {
		return NullFileSystem.getInstance();
	}
```
However, the NullFileSystem is not properly initialized. It uses a static field but sets it in a constructor?
```
public class NullFileSystem extends FileSystem {
	private static IFileSystem instance;
	public static IFileSystem getInstance() {
		return instance;
	}
	public NullFileSystem() {
		super();
		instance = this;
	}

	@Override
	public IFileStore getStore(IPath path) {
		return new NullFileStore(path);
	}

	@Override
	public IFileStore getStore(URI uri) {
		return new NullFileStore(new Path(uri.getPath()));
	}
}
```
I set a breakpoint to see when the constructor was called but this never did seem to happen. I then traced when this NullFileStore was used and that happened in our code. I fixed it there to call new NullFileSystem() before. This seems to fix the problem.

However, it would be nice if this was fixed in the Eclipse code, the current initialization seems incorrect to me.

**Comment by iloveeclipse** [comment] 2024-01-23 17:16
@pkriens : would this below fix your issue?

```
diff --git a/resources/bundles/org.eclipse.core.filesystem/src/org/eclipse/core/internal/filesystem/NullFileSystem.java b/resources/bundles/org.eclipse.core.filesystem/src/org/eclipse/core/internal/filesystem/NullFileSystem.java
index 1d20161..10b86ec 100644
--- a/resources/bundles/org.eclipse.core.filesystem/src/org/eclipse/core/internal/filesystem/NullFileSystem.java
+++ b/resources/bundles/org.eclipse.core.filesystem/src/org/eclipse/core/internal/filesystem/NullFileSystem.java
@@ -31,3 +31,3 @@
 	 */
-	private static IFileSystem instance;
+	private static final IFileSystem INSTANCE = new NullFileSystem();
 
@@ -39,3 +39,3 @@
 	public static IFileSystem getInstance() {
-		return instance;
+		return INSTANCE;
 	}
@@ -47,3 +47,2 @@
 		super();
-		instance = this;
 	}
```

**Comment by pkriens** [comment] 2024-01-23 19:26
Yes. It is basically what dit to fix it in bndtools. 

Thanks.

**Comment by pkriens** [comment] 2024-01-24 07:43
good idea. But if that is the case the static INSTANCE is highly misleading and highly race condition prone.

The pattern to assign a static variable in a public constructor is _really_ bad. In OSGi it  is actually unforgivable :-( The Sun designer that developed the predecessor of OSGi Java Embedded Server, used to call statics _evil_ :-)

**Comment by laeubi** [comment] 2024-01-24 07:48
> I set a breakpoint to see when the constructor was called but this never did seem to happen.

It will happen when someone uses the `null` file system scheme as it is declared in this extension point:

https://github.com/eclipse-platform/eclipse.platform/blob/4c81e2ec59b4ee80674ded36163a471a33ac3cd1/resources/bundles/org.eclipse.core.filesystem/plugin.xml#L12-L17

While I think @iloveeclipse PR is fine here, the bug is more that `org.eclipse.core.filesystem.EFS.getNullFileSystem()` should have call `InternalFileSystemCore.getInstance().getFileSystem("null")` instead.

**Comment by laeubi** [comment] 2024-01-24 08:13
I have now created a variant that gets rid of the singleton altogether:

- https://github.com/eclipse-platform/eclipse.platform/pull/1138

But looking at the code itself I don't see how the NPE can ever happen unless someone is calling `NullFileSystem.getInstance()` (**what is internal API**) versus `EFS.getNullFileSystem()` what always asks for the scheme and will have init the instance before (even though its not nice...).

**Comment by laeubi** [comment] 2024-01-24 08:20
I think the bug is here:

https://github.com/bndtools/bnd/blob/b91bd19ff50270000827c82f8d0affe3fabadf29/bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java#L104

it should be using an own implementation of `IFileStore` instead of using a `NullFileStore` from internal resources API.

**Comment by laeubi** [comment] 2024-01-24 08:31
I changed it from bug > enhancement, as this only occurs if client illegally use internal API.

**Closed** 2024-01-24 10:40 UTC
Labels: enhancement

**Comment by chrisrueger** [comment] 2024-01-24 11:33
Thank you all very  👍

**Comment by pkriens** [comment] 2024-01-24 15:41
This is from https://github.com/bndtools/bnd/issues/4574

This was caused by the fact that the underlying file of the JAR was removed. Since the FileSystem class proposes to return a null file system, the author decided to do this. If only we had a module system that could have private internal implementation classes so this could not have happened?

I've adapted the code to use `EFS.getNullFileSystem()`

That said, this initialization code is a bug. Minor, but still a bug.

**Comment by iloveeclipse** [comment] 2024-01-24 16:13
> That said, this initialization code is a bug. Minor, but still a bug.

Do you mean old code state, or do you see some bug in current master? If later, please give a hint which one.

**Comment by laeubi** [comment] 2024-01-25 06:39
> I've adapted the code to use EFS.getNullFileSystem()

The code is still flawed, see javadoc of IFileStore

https://github.com/eclipse-platform/eclipse.platform/blob/583ce4aee82fdffca6b2a5fa55912c0c67ffe1b9/resources/bundles/org.eclipse.core.filesystem/src/org/eclipse/core/filesystem/IFileStore.java#L276-L281

but `JarFileSystem#getChild("some/entry/in/the/jar").getFileSystem()` will return `NullFileSystem` and not the `JarFileSystem`. In the same sense `JarFileSystem#getChild("some/entry/in/the/jar").toURI()` will return `null:///....` instead of `jarf://...`, also as a user of this filesystem I would not expect that `IFileStore.openInputStream(...)` returns some data.

Beside that I don't know what this `jarf` has any special support, but there is already a `org.eclipse.core.internal.filesystem.zip.ZipFileSystem` / `org.eclipse.core.internal.filesystem.zip.ZipFileStore` (currently only in examples) that might can act as a blueprint on how to implement this, if it is useful in general I think Zip/Jar could/should be just made available as a standard FileSystem and included in the standard eclipse sdk.

**Comment by chrisrueger** [comment] 2024-01-25 10:38
@pkriens FYI : Since your fix in https://github.com/bndtools/bnd/pull/5987 I haven't seen this error anymore (I'm on nightly snapshot   Bndtools 7.1.0.DEV-202401241804). Lot's of branch switches since then.

**Comment by pkriens** [comment] 2024-01-25 10:46
In the mean time I fixed it properly https://github.com/bndtools/bnd/pull/5991/files

Also ran it in the debugger to verify. Seems to be ok now.

**Comment by laeubi** [comment] 2024-01-31 09:42
> If only we had a module system that could have private internal implementation classes so this could not have happened?

See [x-internal:, x-friends:](https://docs.osgi.org/reference/bundle-headers.html) directives, PDE will warn you about (or even error if configured so) I think it even hides such packages if one tries to import them.

**Comment by pkriens** [comment] 2024-03-21 15:46
It turned out the problem was still there ... The NullFileStore was now properly created but the path was not absolute. This caused the getLocationURI() to return null because the URI creation throw a MalformedURLException and then it returned null.

https://github.com/eclipse-platform/eclipse.platform/blob/ebe8db5d9d1c7d231be261d9fd5207dfc94ca9a0/resources/bundles/org.eclipse.core.filesystem/src/org/eclipse/core/internal/filesystem/NullFileStore.java#L118-L126

Changing the constructor to the following would prevent this issue:
```
public NullFileStore(IPath path) {
		Assert.isNotNull(path);
		this.path = path.makeAbsolute();
	}
```
