### ISSUE TITLE
ExpressionTestsPluginUnloading fails since I20220701-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#40] opened 2022-07-03 16:14 UTC
`org.eclipse.core.internal.expressions.tests.ExpressionTestsPluginUnloading` fails since I20220701-1800 on all platforms.

https://download.eclipse.org/eclipse/downloads/drops4/I20220701-1800/testresults/html/org.eclipse.core.expressions.tests_ep425I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
org.eclipse.core.internal.expressions.tests.ExpressionTestsPluginUnloading | test01PluginStopping | Failure | N/A

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.eclipse.core.internal.expressions.tests.ExpressionTestsPluginUnloading.test01PluginStopping(ExpressionTestsPluginUnloading.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
```

**Comment by iloveeclipse** [comment] 2022-07-03 16:39
Regression from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/367, see  https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/381

**Comment by mickaelistria** [comment] 2022-07-03 20:18
I'm not very familiar with this area; but I don't get why would RESOLVED be an invalid value at that stage?

**Comment by laeubi** [comment] 2022-07-04 05:59
> I'm not very familiar with this area; but I don't get why would RESOLVED be an invalid value at that stage?

The javadoc says:

```
/**
 * Tests for cache used in {@link Expressions#isInstanceOf(Object, String)}.
 * <p>
 * <b>WARNING:</b> These tests start, stop, and re-start the <code>com.ibm.icu</code> bundle.
 * Don't include these in another test suite!
*/
```

beside that, if `com.ibm.icu` do not contains an activator, most probably the test do not wants to **restart** but **refresh** the bundle.

By the way: Also `stateToStgring` --> `stateToString`

**Comment by mickaelistria** [comment] 2022-07-04 07:10
The former Orbit variant has `Bundle-ActivationPolicy: lazy` which is not set by the upstream bundle. I don't think this should impact much the initial bundle state and still thinks that bundle state here should be RESOLVED by default, so the test should allow that state as a valid one. Maybe the `Bundle-ActivationPolicy: lazy` causes to turn RESOLVED into ACTIVE earlier.

**Comment by laeubi** [comment] 2022-07-04 07:23
> Maybe the `Bundle-ActivationPolicy: lazy` causes to turn RESOLVED into ACTIVE earlier.

Yes this "activates" the bundle as soon as a class is loaded. But I don't see in the bundle any activator or any declarative component that requires such "activation". `RESOLVED` is a perfectly fine state to use a bundle.

**Comment by mickaelistria** [comment] 2022-07-04 07:35
Anyway, thanks to last change from @iloveeclipse , we have confirmation that bundle state is actually RESOLVED here. I'll update the test accordingly as I believe it's a correct state. One oddity is that this failure cannot be reproduced with Tycho, so Tycho may actually indirectly activate the bundle in some way.

**Comment by mickaelistria** [comment] 2022-07-04 08:14
I merged a patch that's supposed to fix the failure (which I wasn't able to reproduce locally). Let's see what happens...

**Comment by iloveeclipse** [comment] 2022-07-04 19:10
Fails now later:
```
expected:<32> but was:<4>

java.lang.AssertionError: expected:<32> but was:<4>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.eclipse.core.internal.expressions.tests.ExpressionTestsPluginUnloading.test01PluginStopping(ExpressionTestsPluginUnloading.java:56)
```

**Comment by mickaelistria** [comment] 2022-07-04 21:07
I believe it's a continuation of the same issue: since bundle is RESOLVED and not ACTIVE, there is no reason that it turns from RESOLVED to ACTIVE on that line; the expression doesn't need to load the NumberFormat class to return false.

**Comment by mickaelistria** [comment] 2022-07-04 21:14
Next attempt at #43

**Comment by mickaelistria** [comment] 2022-07-05 12:17
Let's keep it open until it's verified.

**Comment by mickaelistria** [comment] 2022-07-05 14:31
Seems now good in https://download.eclipse.org/eclipse/downloads/drops4/I20220705-0600/testresults/html/org.eclipse.core.expressions.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

**Closed by mickaelistria** 2022-07-05 14:31 UTC
Labels: regression
