### ISSUE TITLE
Eclipse.app is modified when installing plugins, invalidating code signature

### ISSUE THREAD

**Issue by nicerloop** [eclipse-platform/eclipse.platform#1267] opened 2024-03-26 20:29 UTC
- [X] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

- install any plugin, for example Cucumber from the Eclipse Marketplace
- quit Eclipse

I tried

- launch Eclipse
=> the application cannot launch as the signature is invalidated by the plugin installed inside Eclipse.app

I expected:
- Eclipse.app to start
- plugins to be installed outside Eclipse.app

But got:
- plugins installed inside Eclipse.app
- Eclipse.app doe not start because the signature is now invalid

## Tested under this environment:
* OS : macOS
* Eclipse IDE/Platform version : 2024-03

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

## Proposed fix

According to https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/misc/multi_user_installs.html , Eclipse can be made to put plugins outside Eclipse.app by making the Eclipse.app/Contents/Eclipse folder read-only (0555).

I tried making the Eclipse.app/Contents/Eclipse folder read-only and observed the desired behaviour.

The Eclipse.app distributed should have this set by default as it impacts all macOS users.

**Comment by sratz** [comment] 2024-09-30 11:29
Yes, this is most likely a duplicate of [#1901](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1901), which should be solved since Eclipse 2024-09.

**Closed by sratz** 2024-09-30 11:29 UTC
Labels: bug
